/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Character3.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Character3 = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Character3.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.wave.play()
    console.log(actions);
})
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <group name="TeethTop001">
            <skinnedMesh name="TeethTopmesh002" geometry={nodes.TeethTopmesh002.geometry} material={materials.Eyemat} skeleton={nodes.TeethTopmesh002.skeleton} />
            <skinnedMesh name="TeethTopmesh002_1" geometry={nodes.TeethTopmesh002_1.geometry} material={materials.Hatmat} skeleton={nodes.TeethTopmesh002_1.skeleton} />
            <skinnedMesh name="TeethTopmesh002_2" geometry={nodes.TeethTopmesh002_2.geometry} material={materials.Pantsmat} skeleton={nodes.TeethTopmesh002_2.skeleton} />
            <skinnedMesh name="TeethTopmesh002_3" geometry={nodes.TeethTopmesh002_3.geometry} material={materials.Pupilmat} skeleton={nodes.TeethTopmesh002_3.skeleton} />
            <skinnedMesh name="TeethTopmesh002_4" geometry={nodes.TeethTopmesh002_4.geometry} material={materials.Shoesmat} skeleton={nodes.TeethTopmesh002_4.skeleton} />
            <skinnedMesh name="TeethTopmesh002_5" geometry={nodes.TeethTopmesh002_5.geometry} material={materials.Skinmat} skeleton={nodes.TeethTopmesh002_5.skeleton} />
            <skinnedMesh name="TeethTopmesh002_6" geometry={nodes.TeethTopmesh002_6.geometry} material={materials.Stashmat} skeleton={nodes.TeethTopmesh002_6.skeleton} />
            <skinnedMesh name="TeethTopmesh002_7" geometry={nodes.TeethTopmesh002_7.geometry} material={materials.Sweatermat} skeleton={nodes.TeethTopmesh002_7.skeleton} />
            <skinnedMesh name="TeethTopmesh002_8" geometry={nodes.TeethTopmesh002_8.geometry} material={materials.Teethmat} skeleton={nodes.TeethTopmesh002_8.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Character3.glb')

export default Character3